// Student Name: Hermela [Your Last Name]
// Student Number: ATE-9479-14
spring.application.name=shopwave-starter
server.port=8080
app.name=ShopWave


spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:shopwavedb
